name = "subscription-manager"
main = "index.js"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "subscription-manager"

[env.staging]
name = "subscription-manager-staging"

# KV 命名空间配置
[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
preview_id = "5d8f7e4b28044c8097e1cd9a553e835c"
id = "5d8f7e4b28044c8097e1cd9a553e835c"

# 定时任务配置 - 每天早上8点检查
[triggers]
crons = ["0 8 * * *"]

# 环境变量（可选，也可以在 Cloudflare Dashboard 中设置）
[vars]
ENVIRONMENT = "production"

[placement]
mode = "smart"